apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  namespace: {{ include "keycloak.namespace" . }}
data: {{ .Values.configmap.data }}
