apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  namespace: {{ include "keycloak.namespace" . }}
stringData: {{ .Values.secret.stringdate }}
